"""initial migration

Revision ID: 20260424190235
Revises: 
Create Date: 2026-04-24T19:02:35.377603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260424190235'
down_revision: Union[str, None] = None
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x_id')
    )
    op.create_index('ix_accounts_is_active', 'accounts', ['is_active'], unique=False)
    op.create_index('ix_accounts_username', 'accounts', ['username'], unique=False)
    op.create_index('ix_accounts_x_id', 'accounts', ['x_id'], unique=False)
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_protocols_is_active', 'protocols', ['is_active'], unique=False)
    op.create_index('ix_protocols_name', 'protocols', ['name'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x_id', sa.String(length=255), nullable=False),
    sa.Column('canonical_x_url', sa.String(length=500), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('retweets_count', sa.Integer(), nullable=True),
    sa.Column('replies_count', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x_id')
    )
    op.create_index('ix_posts_account_id', 'posts', ['account_id'], unique=False)
    op.create_index('ix_posts_canonical_x_url', 'posts', ['canonical_x_url'], unique=False)
    op.create_index('ix_posts_ingested_at', 'posts', ['ingested_at'], unique=False)
    op.create_index('ix_posts_posted_at', 'posts', ['posted_at'], unique=False)
    op.create_index('ix_posts_x_id', 'posts', ['x_id'], unique=False)
    op.create_table('signal_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_x_url', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('research_alpha_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_clusters_is_archived', 'signal_clusters', ['is_archived'], unique=False)
    op.create_index('ix_signal_clusters_primary_x_url', 'signal_clusters', ['primary_x_url'], unique=False)
    op.create_index('ix_signal_clusters_research_alpha_score', 'signal_clusters', ['research_alpha_score'], unique=False)
    op.create_index('ix_signal_clusters_topic', 'signal_clusters', ['topic'], unique=False)
    op.create_table('coverage_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('enrichment_config', sa.Text(), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(), nullable=True),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id')
    )
    op.create_index('ix_coverage_profiles_is_enabled', 'coverage_profiles', ['is_enabled'], unique=False)
    op.create_index('ix_coverage_profiles_protocol_id', 'coverage_profiles', ['protocol_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alpha_score_threshold', sa.Float(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('post_count_threshold', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notification_channel', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_rules_is_active', 'alert_rules', ['is_active'], unique=False)
    op.create_index('ix_alert_rules_protocol_id', 'alert_rules', ['protocol_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('posts_ingested', sa.Integer(), nullable=True),
    sa.Column('posts_new', sa.Integer(), nullable=True),
    sa.Column('posts_updated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_source', 'ingestion_runs', ['source'], unique=False)
    op.create_index('ix_ingestion_runs_started_at', 'ingestion_runs', ['started_at'], unique=False)
    op.create_index('ix_ingestion_runs_status', 'ingestion_runs', ['status'], unique=False)
    op.create_table('post_clusters',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['signal_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'cluster_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_clusters')
    op.drop_table('ingestion_runs')
    op.drop_table('alert_rules')
    op.drop_table('coverage_profiles')
    op.drop_table('signal_clusters')
    op.drop_index('ix_posts_x_id', table_name='posts')
    op.drop_index('ix_posts_posted_at', table_name='posts')
    op.drop_index('ix_posts_ingested_at', table_name='posts')
    op.drop_index('ix_posts_canonical_x_url', table_name='posts')
    op.drop_index('ix_posts_account_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_protocols_name', table_name='protocols')
    op.drop_index('ix_protocols_is_active', table_name='protocols')
    op.drop_table('protocols')
    op.drop_index('ix_accounts_x_id', table_name='accounts')
    op.drop_index('ix_accounts_username', table_name='accounts')
    op.drop_index('ix_accounts_is_active', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
